package com.tayfint.meethub.model;
// default package
// Generated Apr 3, 2018 7:09:29 PM by Hibernate Tools 5.2.0.CR1

import java.util.Calendar;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppMembership generated by hbm2java
 */
@Entity
@Table(name = "app_membership")
public class Membership implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8792977398385098583L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "MembershipTab")
	@TableGenerator(name = "MembershipTab", table = "hibernate_id", pkColumnName = "GEN_KEY", valueColumnName = "GEN_VALUE", pkColumnValue = "MEMBERSHIP_GEN", allocationSize = 1)
	@Column(name = "ID")
	private int id;
	
	@ManyToOne
	@JoinColumn(name = "MEETING_ID")
	private Meeting appMeeting;
	
	@ManyToOne
	@JoinColumn(name = "USER_ID")
	private User appUser;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE")
	private Date createDate = new Date(Calendar.getInstance().getTimeInMillis());
	
	@Column(name = "TYPE_CD")
	private Boolean typeCd;
	
	@Column(name = "IS_ACTIVE")
	private Boolean isActive = true;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TERMINATION_DATE")
	private Date terminationDate;

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Meeting getAppMeeting() {
		return this.appMeeting;
	}

	public void setAppMeeting(Meeting appMeeting) {
		this.appMeeting = appMeeting;
	}

	public User getAppUser() {
		return this.appUser;
	}

	public void setAppUser(User appUser) {
		this.appUser = appUser;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getTypeCd() {
		return this.typeCd;
	}

	public void setTypeCd(Boolean typeCd) {
		this.typeCd = typeCd;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getTerminationDate() {
		return this.terminationDate;
	}

	public void setTerminationDate(Date terminationDate) {
		this.terminationDate = terminationDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((appMeeting == null) ? 0 : appMeeting.hashCode());
		result = prime * result + ((appUser == null) ? 0 : appUser.hashCode());
		result = prime * result + id;
		result = prime * result + ((typeCd == null) ? 0 : typeCd.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Membership other = (Membership) obj;
		if (appMeeting == null) {
			if (other.appMeeting != null)
				return false;
		} else if (!appMeeting.equals(other.appMeeting))
			return false;
		if (appUser == null) {
			if (other.appUser != null)
				return false;
		} else if (!appUser.equals(other.appUser))
			return false;
		if (id != other.id)
			return false;
		if (typeCd == null) {
			if (other.typeCd != null)
				return false;
		} else if (!typeCd.equals(other.typeCd))
			return false;
		return true;
	}

	
}
