package com.tayfint.meethub.model;
// default package
// Generated Apr 3, 2018 7:09:29 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdMembershipType generated by hbm2java
 */
@Entity
@Table(name = "app_rd_membership_type")
public class MembershipType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5785373609754341950L;
	private boolean typeCd;
	private String typeDesc;

	public MembershipType() {
	}

	public MembershipType(boolean typeCd) {
		this.typeCd = typeCd;
	}

	public MembershipType(boolean typeCd, String typeDesc) {
		this.typeCd = typeCd;
		this.typeDesc = typeDesc;
	}

	@Id

	@Column(name = "TYPE_CD", unique = true, nullable = false)
	public boolean isTypeCd() {
		return this.typeCd;
	}

	public void setTypeCd(boolean typeCd) {
		this.typeCd = typeCd;
	}

	@Column(name = "TYPE_DESC", length = 20)
	public String getTypeDesc() {
		return this.typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

}
